export let CONTENT = { //PLEASE UPDATE THE FOLLOWING VALUES WITH YOURS ONES
    NewGame:{
        erroCampoObrigatorio: "At least 2 playes"
    },

    easy_tricks : [
        "Makio",
        "Soul",
        "Mizou",
        "Mistrial",
        "Soul Acid",
        "Pornstar",
        "X-Grind",
        "Fishbrain",
        "Top Soul",
        "Sweatstance",
        "Top Mistrial",
        "Top Acid",
        "Top Pornstar",
        "Frontside",
        "Backside",
        "FS Royalle",
        "BS Royalle",
        "FS Fulltorque",
        "BS Fulltorque",
        "FS Unity",
        "BS Unity"
        
    ],
    
    moderate_tricks : [
        "Alleyoop Makio",
        "Alleyoop Soul",
        "Alleyoop Mizou",
        "Alleyoop Mistrial",
        "Alleyoop Soul Acid",
        "Alleyoop Pornstar",
        "Alleyoop X-Grind",
        "Alleyoop Fishbrain",
        "Alleyoop Top Soul",
        "Kindgrind",
        "Misfit",
        "Alleyoop Top Acid",
        "Alleyoop Top Pornstar",
        "Alleyoop X-Grind",
        "FS Backslide",
        "BS Backslide",
        "FS Torque",
        "BS Torque",
        "FS Savanna",
        "BS Savanna",
        "270 Inspin Frontside",
        "(Fakie) Inspin 270 Backside",
        "270 Inspin FS Royalle",
        "(Fakie) Inspin 270 BS Royalle",
        "270 Inspin FS Fulltorque",
        "(Fakie) Inspin 270 BS Fulltorque",
        "270 Inspin FS Backslide",
        "(Fakie) Inspin 270 BS Backslide",
        "270 Inspin FS Torque",
        "(Fakie) Inspin 270 BS Torque"
    ],

    hard_tricks : [
        "360 Inspin Makio",
        "360 Inspin Soul",
        "360 Inspin Mizou",
        "360 Inspin Mistrial",
        "360 Inspin Soul Acid",
        "360 Inspin Pornstar",
        "360 Inspin X-Grind",
        "Hurricane Fishbrain",
        "Hurricane Top Soul",
        "Hurricane Sweatstance",
        "Hurricane Top Mistrial",
        "Hurricane Top Acid",
        "Hurricane Top Pornstar",
        "Hurricane X-Grind",
        "360 Outspin Makio",
        "360 Outspin Soul",
        "360 Outspin Mizou",
        "360 Outspin Mistrial",
        "360 Outspin Soul Acid",
        "360 Outspin Pornstar",
        "360 Outspin X-Grind",
        "360 Outspin Fishbrain",
        "360 Outspin Top Soul",
        "360 Outspin Sweatstance",
        "360 Outspin Top Mistrial",
        "360 Outspin Top Acid",
        "360 Outspin Top Pornstar",
        "360 Outspin X-Grind",
        "Fullcab Alleyoop Makio",
        "Fullcab Alleyoop Soul",
        "Fullcab Alleyoop Mizou",
        "Fullcab Alleyoop Mistrial",
        "Fullcab Alleyoop Soul Acid",
        "Fullcab Alleyoop Pornstar",
        "Fullcab Alleyoop X-Grind",
        "Fullcab Alleyoop Fishbrain",
        "Fullcab Alleyoop Top Soul",
        "Fullcab Alleyoop Sweatstance",
        "Fullcab Alleyoop Top Mistrial",
        "Fullcab Alleyoop Top Acid",
        "Fullcab Alleyoop Top Pornstar",
        "Fullcab Alleyoop X-Grind",
    ],
  };