export let CONTENT = { //PLEASE UPDATE THE FOLLOWING VALUES WITH YOURS ONES
    NewGame:{
        erroCampoObrigatorio: "At least 2 players",
        commingSoon: 'Coming Soon'
    },
    easy_tricks : [
        "Makio",
        "Soul",
        "Mizou",
        "Mistrial",
        "Acid",
        "Pornstar",
        "X-Grind",
        "Fishbrain",
        "Top Soul",
        "Sweatstance",
        "Top Mistrial",
        "Top Acid",
        "Top Pornstar",
        "Frontside (UFO)",
        "Backside (BS UFO)",
        "Royalle",
        "BS Royalle",
        "Fulltorque",
        "BS Fulltorque",
        "Unity",
        "BS Unity"
    ],
    moderate_tricks : [
        "Alley-oop Makio",
        "Alley-oop Soul",
        "Alley-oop Mizou",
        "Alley-oop Mistrial",
        "Alley-oop Acid",
        "Alley-oop Pornstar",
        "Alley-oop X-Grind",
        "Alley-oop Fishbrain",
        "Alley-oop Top Soul",
        "Kindgrind",
        "Misfit",
        "Alley-oop Top Acid",
        "Alley-oop Top Pornstar",
        "Alley-oop X-Grind",
        "Truespin Makio",
        "Truespin Soul",
        "Truespin Mizou",
        "Truespin Mistrial",
        "Truespin Acid",
        "Truespin Pornstar",
        "Truespin X-Grind",
        "Truespin Fishbrain",
        "Truespin Top Soul",
        "Truespin Kindgrind",
        "Truespin Misfit",
        "Truespin Top Acid",
        "Truespin Top Pornstar",
        "Truespin X-Grind",
        "Backslide",
        "BS Backslide",
        "Torque",
        "BS Torque",
        "Savanna",
        "BS Savanna",
        "270 Inspin Royalle",
        "(Fakie) Inspin 270 BS Royalle",
        "270 Inspin Fulltorque",
        "(Fakie) Inspin 270 BS Fulltorque",
        "270 Inspin Backslide",
        "(Fakie) Inspin 270 BS Backslide",
        "270 Inspin Torque",
        "(Fakie) Inspin 270 BS Torque"
    ],
    hard_tricks : [
        "360 Inspin Makio",
        "360 Inspin Soul",
        "360 Inspin Mizou",
        "360 Inspin Mistrial",
        "360 Inspin Soul Acid",
        "360 Inspin Pornstar",
        "360 Inspin X-Grind",
        "Hurricane Fishbrain",
        "Hurricane Top Soul",
        "Hurricane Sweatstance",
        "Hurricane Top Mistrial",
        "Hurricane Top Acid",
        "Hurricane Top Pornstar",
        "Hurricane X-Grind",
        "360 Outspin Makio",
        "360 Outspin Soul",
        "360 Outspin Mizou",
        "360 Outspin Mistrial",
        "360 Outspin Soul Acid",
        "360 Outspin Pornstar",
        "360 Outspin X-Grind",
        "360 Outspin Fishbrain",
        "360 Outspin Top Soul",
        "360 Outspin Sweatstance",
        "360 Outspin Top Mistrial",
        "360 Outspin Top Acid",
        "360 Outspin Top Pornstar",
        "360 Outspin X-Grind",
        "Fullcab Alley-oop Makio",
        "Fullcab Alley-oop Soul",
        "Fullcab Alley-oop Mizou",
        "Fullcab Alley-oop Mistrial",
        "Fullcab Alley-oop Soul Acid",
        "Fullcab Alley-oop Pornstar",
        "Fullcab Alley-oop X-Grind",
        "Fullcab Alley-oop Fishbrain",
        "Fullcab Alley-oop Top Soul",
        "Fullcab Alley-oop Sweatstance",
        "Fullcab Alley-oop Top Mistrial",
        "Fullcab Alley-oop Top Acid",
        "Fullcab Alley-oop Top Pornstar",
        "Fullcab Alley-oop X-Grind",
        "Fullcab Truespin Makio",
        "Fullcab Truespin Soul",
        "Fullcab Truespin Mizou",
        "Fullcab Truespin Mistrial",
        "Fullcab Truespin Soul Acid",
        "Fullcab Truespin Pornstar",
        "Fullcab Truespin X-Grind",
        "Fullcab Truespin Fishbrain",
        "Fullcab Truespin Top Soul",
        "Fullcab Truespin Sweatstance",
        "Fullcab Truespin Top Mistrial",
        "Fullcab Truespin Top Acid",
        "Fullcab Truespin Top Pornstar",
        "Fullcab Truespin X-Grind",
    ]
  };